app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
# Back Office
Route::group(['domain' => 'bo'.env('SESSION_DOMAIN'), 'middleware' => 'bo'], function () {
    Route::get('/', 'Admin\PageController@index');
    # Quizz
    Route::resource('quizz', 'Admin\QuizzController', ['except' => ['show']]);
    Route::group(['prefix' => '/quizz/{id}'], function(){
        Route::resource('answer', 'Admin\AnswerController');
        Route::resource('lang', 'Admin\QuizzLangController', ['except' => ['show']]);
    });
});

Route::get('/', 'PageController@home')->name('home');
Route::get('/me', 'PageController@me')->middleware('auth');

Route::get('/q/{slug}', 'QuizzController@show');
Route::get('/r/{slug}', 'QuizzController@result');


# Social Auth
Route::get('auth/facebook', 'Auth\AuthSocialController@login');
Route::get('auth/facebook/callback', 'Auth\AuthSocialController@facebookCallback');
Route::get('/logout', 'Auth\AuthSocialController@logout');

app/Http/Controllers/Admin/QuizzController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Quizz\QuizzLang;
use Illuminate\Http\Request;
use App\Quizz\Quizz;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Hash;

class QuizzController extends Controller
{
    public function index(){
        $quizzs = Quizz::orderBy('id', 'desc')->get()->load('quizzLangs');
        return view('back.quizz.index', compact('quizzs'));
    }

    public function destroy(Request $request, $id){
        if($request->ajax()){
            $quizz = Quizz::findOrFail($id);
            $quizz->delete();
            return ['success' => true];
        }else{
            return abort(404);
        }
    }

    public function create(){
        return view('back.quizz.create');
    }

    public function store(Request $request){
        $validator = Validator::make($request->all(), [
            'slug' => 'required|unique:quizzs,slug|min:5',
            'gender' => 'required|in:all,male,female',
            'image' => 'required|image|max:2048|dimensions:min_width=800,min_height=400'
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }else{
            // On encode notre slug et on regarde si il existe ou non en BDD
            $slug = str_slug(Input::get('slug'));
            if(Quizz::where('slug', '=', $slug)->exists()) {
                $validator->errors()->add('slug', 'Ce slug existe déjà !');
                return back()->withErrors($validator)->withInput();
            }else{
                $image_name =  'q_'.time().str_random(rand(15, 20)).'.jpg';
                $image = Image::make(Input::file('image'))->save(public_path('img/quizz/'.$image_name));
                $quizz = new Quizz();
                $quizz->slug = $slug;
                if(Input::get('visible')) $quizz->visible = 1;
                $quizz->image = $image_name;
                $quizz->gender = Input::get('gender');
                $quizz->save();

                foreach(Input::get('langs') as $key => $value){
                    $lang = new QuizzLang();
                    $lang->quizz_id = $quizz->id;
                    $lang->lang = $value;
                    $lang->save();
                }

                return redirect('quizz')->with('added_quizz', true);
            }
        }
    }

    public function edit($id){
        $quizz = Quizz::findOrFail($id);
        $langs = $quizz->quizzLangs()->get();
        $results = $visits = collect();
        $answers = $quizz->answers()->get();
        foreach($langs as $key => $value){
            $results = $results->merge($value->quizzResults()->get());
            $visits = $visits->merge($value->quizzVisits()->get());
        }
        return view('back.quizz.edit', compact('quizz', 'langs', 'visits', 'results', 'answers'));
    }

    public function update(Request $request, $id){
        $validator = Validator::make($request->all(), [
            'slug' => 'required|min:5',
            'gender' => 'required|in:all,male,female',
            'image' => 'image|max:2048|dimensions:min_width=800,min_height=400'
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }else{
            // On encode notre slug et on regarde si il existe ou non en BDD
            $slug = str_slug(Input::get('slug'));
            if(Quizz::where('slug', '=', $slug)->whereNotIn('id', [$id])->exists()) {
                $validator->errors()->add('slug', 'Ce slug existe déjà !');
                return back()->withErrors($validator)->withInput();
            }else{
                $quizz = Quizz::findOrFail($id);
                if($request->hasFile('image')){
                    $image_name =  'q_'.time().str_random(rand(15, 20)).'.jpg';
                    $image = Image::make(Input::file('image'))->save(public_path('img/quizz/'.$image_name));
                    $quizz->image = $image_name;
                }
                $quizz->slug = $slug;
                if(Input::get('visible')) $quizz->visible = 1; else $quizz->visible = 0;
                $quizz->gender = Input::get('gender');
                $quizz->save();

                return back()->with('edited_quizz', true);
            }
        }
    }
}

app/Http/Controllers/QuizzController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Quizz\QuizzLang;
use App\Quizz\QuizzVisit;
use Illuminate\Support\Facades\Auth;
use App\Quizz\QuizzResult;

class QuizzController extends Controller
{
    public function show(Request $request, $slug){
        // Tout les quizz en ligne dans la langue du client
        // Attention le select est à faire dans cette ordre sinon le ID de lang_quizz va être remplacer par celui de quizzs
        $quizzs = QuizzLang::visible()->with('quizzTranslations')->select('quizzs.*', 'quizz_langs.*');

        // On veut les 3 meilleurs quizzs parmis ceux là en fonction de leur nombre de fois joué durant ces 2 semaines

        $featuredQuizzs = $quizzs->get()->load('quizzResults2WeeksCount', 'quizzVisits2WeeksCount')->sortByDesc(function($quizz){
            $plays = $quizz->quizzResults2WeeksCount;
            $visits = $quizz->quizzVisits2WeeksCount;
            return $plays * 5 + $visits;
        })->take(2);

        $quizzs = $quizzs->orderby('quizzs.id', 'desc')->paginate(6);
        // Afficher plus de quizz en ajax
        if($request->ajax()){
            return view('front.quizz.quizzs', compact('quizzs'));
        }

        $quizz = QuizzLang::visible()
                ->with('quizzTranslations')
                ->select('quizzs.*', 'quizz_langs.*')
                ->where('slug', $slug)
                ->firstOrFail();
        $this->updateVisit($request, $quizz->id);

        return view('front.quizz.show', compact('quizz', 'quizzs', 'featuredQuizzs'));
    }

    public function updateVisit(Request $request, $quizz_lang_id){
        // On vérifie si il n'y a pas eu de visite par le même utilisateur dans les 2 dernières minutes
        $nb_visits = QuizzVisit::where('ip', $request->ip())->where('quizz_lang_id', $quizz_lang_id)->where('created_at', '>=', Carbon::now()->subMinute(2))->count();
        if($nb_visits === 0){
            $visit = new QuizzVisit();
            $visit->user_id = Auth::user()->id;
            $visit->quizz_lang_id = $quizz_lang_id;
            $visit->ip = $request->ip();
            $visit->save();
        }
    }

    public function result(Request $request, $slug){
        // Tout les quizz en ligne dans la langue du client
        // Attention le select est à faire dans cette ordre sinon le ID de lang_quizz va être remplacer par celui de quizzs
        $quizzs = QuizzLang::visible()->with('quizzTranslations')->select('quizzs.*', 'quizz_langs.*');

        // On veut les 3 meilleurs quizzs parmis ceux là en fonction de leur nombre de fois joué durant ces 2 semaines

        $featuredQuizzs = $quizzs->get()->load('quizzResults2WeeksCount', 'quizzVisits2WeeksCount')->sortByDesc(function($quizz){
            $plays = $quizz->quizzResults2WeeksCount;
            $visits = $quizz->quizzVisits2WeeksCount;
            return $plays * 5 + $visits;
        })->take(2);

        $quizzs = $quizzs->orderby('quizzs.id', 'desc')->paginate(6);
        // Afficher plus de quizz en ajax
        if($request->ajax()){
            return view('front.quizz.quizzs', compact('quizzs'));
        }

        $result = QuizzResult::where('slug', $slug)->with('user')->firstOrFail();
        $quizz = QuizzLang::visible()
            ->with('quizzTranslations')
            ->select('quizzs.*', 'quizz_langs.*')
            ->where('quizz_langs.id', $result->quizz_lang_id)
            ->firstOrFail();

        return view('front.quizz.result', compact('quizz', 'result', 'quizzs', 'featuredQuizzs'));

    }
}

resources/views/back/quizz/edit.blade.php
@extends('back.layouts.default', ['active' => 'quizz'])

@section('title') Modification Quizz @endsection

@section('content')
    <div class="row">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="content">
                        <h4>
                            Réponses possibles <small><span class="label label-info">{{ count($answers) }}</span></small>
                            <a class="pull-right btn btn-round btn-danger btn-fill" href="{{ url('quizz/'.$quizz->id.'/answer/create') }}"><i class="fa fa-plus"></i></a>
                        </h4>
                        <hr>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Fond</th>
                                    <th>En Ligne?</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($answers as $answer)
                                    <tr>
                                        <td>{{ $answer->id }}</td>
                                        <td><img src="{{ url('img/answer/'.$answer->background) }}" class="img-responsive img-raised img-rounded" style="max-width: 400px"></td>
                                        <td>@if($answer->visible) <span class="label label-success">Oui</span> @else <span class="label label-danger">Non</span> @endif</td>
                                        <td>
                                            <a rel="tooltip" title="" class="btn btn-simple btn-info btn-icon table-action builder" href="{{ url('quizz/'.$quizz->id.'/answer/'.$answer->id) }}" data-original-title="Construire"><i class="fa fa-puzzle-piece"></i></a>
                                            <a rel="tooltip" title="" class="btn btn-simple btn-warning btn-icon table-action edit" href="{{ url('quizz/'.$quizz->id.'/answer/'.$answer->id.'/edit') }}" data-original-title="Modifier"><i class="fa fa-edit"></i></a>
                                            <a rel="tooltip" title="" class="btn btn-simple btn-danger btn-icon table-action remove" href="javascript:void(0)" data-original-title="Supprimer"><i class="fa fa-remove"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="content">
                        <h4>
                            Langues du quizz <small><span class="label label-info">{{ count($langs) }}</span></small>
                            <a class="pull-right btn btn-round btn-danger btn-fill" href="{{ url('quizz/'.$quizz->id.'/lang/add') }}"><i class="fa fa-plus"></i></a>
                        </h4>
                        <hr>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Langue</th>
                                    <th>En Ligne?</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($langs as $lang)
                                    <tr>
                                        <td>{{ $lang->id }}</td>
                                        <td><img src="{{ url('img/flags/'.$lang->lang.'.png') }}"></td>
                                        <td>@if($lang->visible) <span class="label label-success">Oui</span> @else <span class="label label-danger">Non</span> @endif</td>
                                        <td>
                                            @if($lang->visible)
                                                <a rel="tooltip" title="" class="btn btn-simple btn-success btn-icon table-action offline" href="{{ url('quizz/'.$quizz->id.'/lang/'.$lang->id.'/edit') }}" data-original-title="Mettre hors-ligne"><i class="fa fa-toggle-on"></i></a>
                                            @else
                                                <a rel="tooltip" title="" class="btn btn-simple btn-warning btn-icon table-action online" href="{{ url('quizz/'.$quizz->id.'/lang/'.$lang->id.'/edit') }}" data-original-title="Mettre en ligne"><i class="fa fa-toggle-off"></i></a>
                                            @endif
                                            <a rel="tooltip" title="" class="btn btn-simple btn-danger btn-icon table-action remove" href="javascript:void(0)" data-original-title="Supprimer"><i class="fa fa-remove"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="content">
                        <h3>
                            @if(!empty($title = $quizz->quizzLangs()->where('lang', strtolower(App::getLocale()))->where('visible', true)->first()))
                                {{ $title->translations->title }}
                            @else
                                {{ $quizz->slug }}
                            @endif
                            <small><span class="label label-info">ID: {{ $quizz->id }}</span></small>
                        </h3>
                        <hr>
                        <div clas="col-md-12 col-md-offset-1">
                            {!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->action( route('quizz.update', $quizz) )->put()->enctype("multipart/form-data") !!}
                            {!! BootForm::bind($quizz) !!}
                            {!! BootForm::text('Slug', 'slug') !!}
                            {!! BootForm::select('Sexe', 'gender')->options(['all' => 'Homme et Femme', 'male' => 'Homme', 'female' => 'Femme']) !!}
                            {!! BootForm::select('En Ligne?', 'visible')->options([false => 'Non', 1 => 'Oui']) !!}
                            <div class="form-group">
                                <label class="col-sm-4 col-lg-2 control-label" for="visible">Aperçu</label>
                                <div class="col-sm-8 col-lg-10">
                                    <img src="{{ url('img/quizz/'.$quizz->image) }}" class="img-responsive img-rounded img-raised">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 col-lg-2 control-label" for="visible">Photo</label>
                                <div class="col-sm-8 col-lg-10">
                                    <label><small>Minimum 800x400 (2MB MAX)</small></label>
                                    <input 	type='file'
                                              class='input-ghost'
                                              name='image'
                                              style='visibility:hidden; height:0'
                                              onchange="$(this).next().find('input').val(($(this).val()).split('\\').pop());">
                                    <div class="input-group input-file" name="Fichier_1">
                                        <span class="input-group-btn">
                                            <button 	class="btn btn-info btn-info btn-fill btn-choose"
                                                       type="button"
                                                       onclick="$(this).parents('.input-file').prev().click();">Choisir</button>
                                        </span>
                                        <input 	type="text"
                                                  class="form-control"
                                                  placeholder='Choisissez un fichier...'
                                                  style="cursor:pointer"
                                                  onclick="$(this).parents('.input-file').prev().click(); return false;"
                                        />
                                    </div>
                                </div>
                            </div>
                            {!! BootForm::submit('Modifier')->class('btn btn-rounded btn-fill pull-right') !!}
                            {!! BootForm::close() !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="content">
                        <h4>Les 30 dernières visites <small><span class="label label-info">total: {{ count($visits) }}</span></small></h4>
                        <hr>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Utilisateur</th>
                                    <th>Langue</th>
                                    <th>IP</th>
                                    <th>Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($visits->take(30) as $visit)
                                <tr>
                                    <td>{{ $visit->id }}</td>
                                    <td><a href="{{ url('user/'.$visit->user()->first()->id.'/edit') }}">{{ $visit->user()->first()->name }}</a></td>
                                    <td><img src="{{ url('img/flags/'.$visit->quizzLang()->first()->lang.'.png') }}"></td>
                                    <td>{{ $visit->ip }}</td>
                                    <td>{{ \Carbon\Carbon::parse($visit->created_at)->diffForHumans() }}</td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="content">
                        <h4>Les 30 derniers résultats générés <small><span class="label label-info">{{ count($results) }}</span></small></h4>
                        <hr>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Utilisateur</th>
                                    <th>Image</th>
                                    <th>Langue</th>
                                    <th>IP</th>
                                    <th>Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($results->take(30) as $result)
                                    <tr>
                                        <td>{{ $result->id }}</td>
                                        <td><a href="{{ url('user/'.$result->user()->first()->id.'/edit') }}">{{ $result->user()->first()->name }}</a></td>
                                        <td><img style="max-width: 150px" src="{{ url('img/result/'.$result->image) }}" class="img-responsive img-raised img-rounded"></td>
                                        <td><img src="{{ url('img/flags/'.$result->quizzLang()->first()->lang.'.png') }}"></td>
                                        <td>{{ $result->ip }}</td>
                                        <td>{{ \Carbon\Carbon::parse($result->created_at)->diffForHumans() }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript">
        @if(Session::has('edited_quizz'))
            $.notify({
            icon: 'pe-7s-bell',
            message: "<b>Félicitation</b> - votre quizz a bien été modifié."

        },{
            type: 'success',
            timer: 4000
        });
        @endif
    </script>
@endsection